

# FROM node:latest as node
# WORKDIR /app
# COPY . .
# RUN npm install
# RUN npm run build --prod

# FROM nginx:alpine
# COPY --from=node /app/dist/angular7tutorial /usr/share/nginx/html

FROM node:11.15.0-alpine as build-step
WORKDIR /app
COPY ./package.json . 
RUN npm install
COPY . .
EXPOSE 4200
CMD npm run start

