pipeline {
  agent any
 
  tools {nodejs "node"}
 
  stages {
    stage('Cloning Git') {
      steps {
        git 'https://github.com/asthagaur1/angular.git'
      }
    }
    stage('Checkout') {
        steps {
            checkout([$class: 'GitSCM', 
        branches: [[name: '*/ui']], 
        doGenerateSubmoduleConfigurations: false, 
        extensions: [], 
        submoduleCfg: [], 
        userRemoteConfigs: [[url: 'https://github.com/asthagaur1/angular.git']]])   
        }
    }
     stage('Install dependencies') {
      steps {
        bat 'npm install'
      }
    }
    stage('Build') {
      steps {
        bat 'npm start'
      }
    }
     stage('Test') {
      steps {
        bat 'npm test'
      }
    }
  }
}